/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_llw_demo_call_jni_jni_JNI */

#ifndef _Included_com_example_llw_demo_call_jni_jni_JNI
#define _Included_com_example_llw_demo_call_jni_jni_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_llw_demo_call_jni_jni_JNI
 * Method:    hellofromc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_llw_demo_1call_1jni_jni_JNI_hellofromc
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
